name = "link-lengthener"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-06-21"

[assets]
directory = ".svelte-kit/cloudflare/_app"
binding = "ASSETS"
run_worker_first = true

[[kv_namespaces]]
binding = "KV" # This must match the binding used in your code
id = "af1e270efc224e22b091a70c911b7c2b" # Replace with your actual KV namespace ID

[env.production]
[[env.production.kv_namespaces]]
binding = "KV"
id = "af1e270efc224e22b091a70c911b7c2b"

[env.preview]
[[env.preview.kv_namespaces]]
binding = "KV"
id = "af1e270efc224e22b091a70c911b7c2b"

[observability.logs]
enabled = true
