name = 'link-lengthener'
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-06-21"

[assets]
directory = ".svelte-kit/cloudflare/_app"
binding = "ASSETS"
run_worker_first = true

[[env.production.kv_namespaces]]
binding = "KV"
id = "e13cc64435034a51a9c99d83102c967d"

[[env.preview.kv_namespaces]]
binding = "URL_SHORTENER"
id = "test"

[observability.logs]
enabled = true
