name = 'link-lengthener'
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-06-21"

[assets]
directory = ".svelte-kit/cloudflare/_app"
binding = "ASSETS"
run_worker_first = true

[[env.production.kv_namespaces]]
binding = "LINKS"
id = "af1e270efc224e22b091a70c911b7c2b"

[[env.preview.kv_namespaces]]
binding = "LINKS"
id = "af1e270efc224e22b091a70c911b7c2b"

[observability.logs]
enabled = true
